name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r server/requirements.txt
        pip install pytest

    - name: Run secret scanner
      run: python scripts/check_secrets.py

    - name: Smoke test imports
      run: |
        python -c "import fastapi, pydantic, joblib, numpy, pandas; print('✅ imports ok')"
